# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [  node-project ]
  pull_request:
    branches: [  node-project ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
            node-version: '12.x'

      - name: Perform install, build and start commands
        run: |
            npm install
            tsc
            npm run start --if-present
